# Generated by Django 4.1.7 on 2023-03-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Becher',
            new_name='Techert',
        ),
    ]
