# Generated by Django 4.1.7 on 2023-04-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
